version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      POSTGRES_DB: air_quality
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: air_quality
      DB_USER: etl_user
      DB_PASS: etl_password

    env_file:
      - .env

volumes:
  postgres_data:
